/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDfm78f2PX4qkh9qx0Q7MA",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "products": a.model({
        id: a.id().required(),
        updated_at: a.string(),
        created_at: a.string(),
        price_in_cents: a.integer().required(),
        name: a.string().required(),
        description: a.string()
    }).identifier([
        "id"
    ])
});
